######################## default configuration ####################
baseURL = "https://perceptioninterval.com/"
title = "Perception Interval"
theme = "twenty-twenty-hugo"
languageName = "En"
languageCode = "en-us"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # disable language from here
# google analytics
googleAnalytics = "" # example : UA-123-45


############################## Output ###############################
[outputs]
home = ["HTML", "RSS", "JSON"]

# unsafe html
[markup.goldmark.renderer]
[markup.goldmark.renderer]
unsafe = true
[[menu.desktop]]
URL = "contact/"
name = ""
weight = 1
[[menu.main]]
URL = ""
name = "Home"
weight = 1
[[menu.main]]
URL = "about/"
name = ""
weight = 2
[[menu.main]]
URL = "blog/"
name = ""
weight = 3
[[menu.main]]
URL = "contact/"
name = "Contact"
weight = 4
[[menu.main]]
URL = "sample-page/"
name = "Green NFTs"
weight = 5
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Michael Espero"
description = "This is meta description"
[params.banner]
heading = "Blending Intuition With Data"
image = "images/2020-landscape-1-2.png"
[params.blog]
heading = "End-to-end data science and analytics"
[params.call_to_action]
button_label = ""
button_url = ""
content = ""
enable = true
title = ""
[params.cookies]
enable = true
expire_days = 2
[params.favicon]
favicon = "images/favicon.png"
[params.footer]
content = "End-to-end data science and analytics"
copyright = "Copyright &copy; 2023 Perception Interval"
title = "Perception Interval"
[params.gallery]
enable = true
[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"
[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"


[taxonomies]
author = "author"
category = "categories"
tag = "tags"
